module.exports = {
  help: require('./help'),
  auth: require('./auth'),
  init: require('./init'),
  register: require('./register'),
  scaffold: require('./scaffold'),
  describe: require('./describe'),
  // hiding for now until we can work out the bugs
  // watch: require('./watch'),
  test: require('./test'),
  link: require('./link'),
  apps: require('./apps'),
  versions: require('./versions'),
  validate: require('./validate'),
  build: require('./build'),
  upload: require('./upload'),
  deploy: require('./deploy'),
  promote: require('./promote'),
  migrate: require('./migrate'),
  deprecate: require('./deprecate'),
  collaborate: require('./collaborate'),
  invite: require('./invite'),
  history: require('./history'),
  logs: require('./logs'),
  env: require('./env'),
};
