module.exports = {
  help: require('./help'),
  auth: require('./auth'),
  create: require('./create'),
  scaffold: require('./scaffold'),
  describe: require('./describe'),
  link: require('./link'),
  apps: require('./apps'),
  versions: require('./versions'),
  validate: require('./validate'),
  build: require('./build'),
  upload: require('./upload'),
  push: require('./push'),
  deploy: require('./deploy'),
  migrate: require('./migrate'),
  deprecate: require('./deprecate'),
  collaborate: require('./collaborate'),
  invite: require('./invite'),
  history: require('./history'),
  logs: require('./logs'),
  env: require('./env'),
};
